"""
Query API routes — RAG endpoint and SSE streaming endpoint.
"""
import json
import logging
import time
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.database import get_db
from app.middleware.latency import (
    record_embedding_latency,
    record_llm_latency,
    record_vector_search_latency,
)
from app.schemas.query import QueryRequest, RAGResponse, LatencyMetrics
from app.services.cache import (
    get_cached_embedding,
    get_cached_rag_response,
    set_cached_embedding,
    set_cached_rag_response,
)
from app.services.embedding import embed_query
from app.services.rag_engine import generate_rag_response, stream_rag_response
from app.services.vector_store import similarity_search

logger = logging.getLogger(__name__)
settings = get_settings()

router = APIRouter(prefix="/query", tags=["Query"])


@router.post("/", response_model=RAGResponse)
async def query_documents(
    request: QueryRequest,
    db: AsyncSession = Depends(get_db),
) -> RAGResponse:
    """
    Main RAG query endpoint.

    Pipeline:
    1. Check Redis cache for full response
    2. Embed the query (or get from embedding cache)
    3. Vector similarity search (top-K)
    4. Generate LLM response with citations
    5. Cache and return result
    """
    # Check full RAG cache
    cache_key = request.query + (str(request.document_ids) if request.document_ids else "")
    cached_response = await get_cached_rag_response(cache_key)
    if cached_response:
        logger.info("Full RAG cache hit for query")
        response_obj = RAGResponse(**cached_response)
        response_obj.latency.cached = True
        return response_obj

    # Step 1: Embed query (with embedding cache)
    t0 = time.perf_counter()
    query_embedding = await get_cached_embedding(request.query)
    if query_embedding is None:
        query_embedding = await embed_query(request.query)
        await set_cached_embedding(request.query, query_embedding)
    embedding_ms = (time.perf_counter() - t0) * 1000
    record_embedding_latency(embedding_ms)

    # Step 2: Vector similarity search
    t1 = time.perf_counter()
    sources = await similarity_search(
        session=db,
        query_embedding=query_embedding,
        top_k=request.top_k,
        document_ids=request.document_ids,
    )
    vector_ms = (time.perf_counter() - t1) * 1000
    record_vector_search_latency(vector_ms)

    if not sources:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No relevant document chunks found. Please upload documents first.",
        )

    # Step 3: Generate RAG response
    t2 = time.perf_counter()
    rag_response = await generate_rag_response(
        query=request.query,
        sources=sources,
        embedding_ms=embedding_ms,
        vector_search_ms=vector_ms,
    )
    llm_ms = (time.perf_counter() - t2) * 1000
    record_llm_latency(llm_ms)

    # Cache the response
    await set_cached_rag_response(cache_key, rag_response.model_dump(mode="json"))

    return rag_response


@router.post("/stream")
async def stream_query_documents(
    request: QueryRequest,
    db: AsyncSession = Depends(get_db),
) -> StreamingResponse:
    """
    Streaming RAG endpoint using Server-Sent Events (SSE).
    Streams tokens as they are generated by Gemini.
    """
    # Embed query
    t0 = time.perf_counter()
    query_embedding = await get_cached_embedding(request.query)
    if query_embedding is None:
        query_embedding = await embed_query(request.query)
        await set_cached_embedding(request.query, query_embedding)
    embedding_ms = (time.perf_counter() - t0) * 1000

    # Vector search
    t1 = time.perf_counter()
    sources = await similarity_search(
        session=db,
        query_embedding=query_embedding,
        top_k=request.top_k,
        document_ids=request.document_ids,
    )
    vector_ms = (time.perf_counter() - t1) * 1000

    if not sources:
        async def _error_stream():
            yield f"data: {json.dumps({'type': 'error', 'content': 'No relevant documents found.'})}\n\n"
        return StreamingResponse(_error_stream(), media_type="text/event-stream")

    return StreamingResponse(
        stream_rag_response(
            query=request.query,
            sources=sources,
            embedding_ms=embedding_ms,
            vector_search_ms=vector_ms,
        ),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
